### ISSUE TITLE
docs: Tutorial cloudflare pages with an unaccessible footer

### ISSUE THREAD

**Issue by yzs981130** [PersiaML/PERSIA#153]
Currently, the tutorial website in README points to [tutorial pages](https://persiaml-tutorials.pages.dev/), with a footer of "Found a bug? Edit this file on GitHub."

However, the link should break and end up with a 404 because of the _private_ repository visibility of the [tutorials repo](https://github.com/PersiaML/tutorials/) from the public view, which is expected to be fixed.

**Comment by NOBLES5E** [comment]
Thanks for reporting! The tutorial repo is public now. 👍
