### ISSUE TITLE
Missing .env file?

### ISSUE THREAD

**Issue by Tokkiu** [PersiaML/PERSIA#188]
Hi, I am using PERSIA to test on my GPU server and there's some error.
I have tried three methods to use it.

1. Directly run docker image as `docker-compose -f docker-compose.yml up`
   Encountered with `ERROR: Couldn't find env file: /xx/xx/persia/examples/docker-compose/.env`

2. Using make command as`/xx/xx/persia/examples/docker-compose$ make run`
   Encountered with `open /xx/xx/persia/examples/docker-compose/.env: no such file or directory`

3. I even tried to run train.py manually but also failed as `ENABLE_CUDA=1 python train.py`
    I set the rank, device_id, world_size manually and torch.cuda.is_available() return True
    Encountered with 
    `2021-11-27 02:48:45,834 INFO     [train.py:35] test dataset size is 128
    Traceback (most recent call last):
      File "train.py", line 116, in <module>
        with TrainCtx(
      File "/opt/conda/lib/python3.8/site-packages/persia/ctx.py", line 619, in __init__
        super(TrainCtx, self).__init__(PreprocessMode.TRAIN, *args, **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/persia/ctx.py", line 224, in __init__
        super(EmbeddingCtx, self).__init__(*args, **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/persia/ctx.py", line 109, in __init__
        self.common_context = PersiaCommonContext(
    OverflowError: can't convert negative int to unsigned`
   It's quite weird.

Is there any suggestion or missing documents?
Thank you!

**Comment by NOBLES5E** [comment]
Thanks for reporting! @williamstar please take a look.

**Comment by williamstar** [comment]
I sorry that the .env file is ignore by the .gitignore. I will fix this problem after update .env filename to specific .docker_env.
