### ISSUE TITLE
Generate criteo syn dataset

### ISSUE THREAD

**Issue by BLue1881euLB** [PersiaML/PERSIA#196]
Hello，Could you tell us how to generate your criteo_syn dataset those used in your experiment?

**Comment by williamstar** [comment]
Our synthesis method is simple, each criteo id will be used to generate 1000 new IDs, which can be formalized as: ID_new = ID_TOTAL_NUM X i + ID_old , i=0,...,999.

**Comment by BLue1881euLB** [comment]
> 
do it satisfy long tail distribution?

**Comment by williamstar** [comment]
Of course

**Comment by williamstar** [comment]
Yes
