### ISSUE TITLE
Where is EmbeddingWorkerNatsServicePublisher?

### ISSUE THREAD

**Issue by zxgx** [PersiaML/PERSIA#218]
It seems that EmbeddingWorkerNatsServicePublisher is quite important to maintain the communication among data context, embedding servers/workers and nn workers. But I couldn't find the exact file for this class. Could you please tell where the class is defined and implemented?

**Comment by snowpeakz** [comment]
https://github.com/PersiaML/PERSIA/blob/9c330624726843cb943e2293ce7d3a4b170e9474/rust/persia-embedding-server/src/embedding_worker_service/mod.rs#L1498-L1561

`EmbeddingWorkerNatsServicePublisher ` is generated by the marco `persia_nats_marcos::service`.  A `Publisher` sends messages to `Responder` which is similar to a rpc client.

**Comment by zxgx** [comment]
Cool! I've also found that. Sorry for my poor knowledge about rust.
