### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by NOBLES5E** [PersiaML/PERSIA#23]
lack of docs:

- https://persiaml.readthedocs.io/en/latest/autoapi/persia/sparse/index.html
- https://persiaml.readthedocs.io/en/latest/autoapi/persia/ctx/index.html
- https://persiaml.readthedocs.io/en/latest/autoapi/persia/env/index.html
- https://persiaml.readthedocs.io/en/latest/autoapi/persia/logger/index.html
- https://persiaml.readthedocs.io/en/latest/autoapi/persia/wrapper/index.html

some of them should be hidden, such as `persia.wrapper.logger`, since users are not expected to use them.

**Comment by williamstar** [comment]
Can close the issue now?

**Comment by NOBLES5E** [comment]
The overall format looks fine now. The writing still needs to be improved. I will comment on the code so that we can start improving the writing.
